changelog:
  categories:
  - title: Breaking Changes 😤
    labels:
    - breaking-change
  - title: Exciting New Features 🎉
    labels:
    - feature
  - title: Bug fixes 🐜
    labels:
    - bug
  - title: Other Changes other
    labels:
       - "*"
